apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cake-delight

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
        - name: order-service

          image: cake-delight-order-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5002

          env:
            - name: PORT
              value: "5002"

            - name: MONGO_URI
              value: "mongodb://mongodb:27017/orderdb"

            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:5001"

            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"

          readinessProbe:
            tcpSocket:
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 5002
            initialDelaySeconds: 20
            periodSeconds: 10