apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cake-delight

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-service

  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service

          image: cake-delight-notification-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5004

          env:
            - name: PORT
              value: "5004"

            - name: MONGO_URI
              value: "mongodb://mongodb:27017/notificationdb"

            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"

            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_USER

            - name: MAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: MAIL_APP_PASSWORD

          readinessProbe:
            tcpSocket:
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: 5004
            initialDelaySeconds: 20
            periodSeconds: 10