apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cake-delight

spec:
  selector:
    app: notification-service

  ports:
    - name: http
      port: 5004
      targetPort: 5004

  type: ClusterIP