apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: cake-delight

spec:
  selector:
    app: rating-service

  ports:
    - name: http
      port: 5003
      targetPort: 5003

  type: ClusterIP