apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: cake-delight
spec:
  replicas: 1

  selector:
    matchLabels:
      app: catalog-service

  template:
    metadata:
      labels:
        app: catalog-service

    spec:
      containers:
        - name: catalog-service

          image: cake-delight-catalog-service:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5001

          env:
            - name: PORT
              value: "5001"

            - name: MONGO_URI
              value: "mongodb://mongodb:27017/catalog_db"